### ISSUE TITLE
completley crap 

### ISSUE THREAD

**Issue by willothen** [michaelm2006/Computer-Science-NEA#55]
![image](https://github.com/user-attachments/assets/6ade06d9-7bad-487b-8505-624a718712a1)
![image](https://github.com/user-attachments/assets/90901c71-11e4-4131-961e-6039e2719059)
couldnt even get 3 correct letters

**Comment by willothen** [comment]
i agree. so ass. how is this going to be an example.

**Comment by michaelm2006** [comment]
Don't start with a crap word 👍
